# Generated by Django 3.0.7 on 2020-06-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'permissions': [('can_add_projectfile', 'Может добавлять файлы проектов'), ('can_del_projectfile', 'Может удалять файлы проектов'), ('can_upd_projectfile', 'Может изменять файлы проектов')],
            },
        ),
    ]
