# Generated by Django 3.0.7 on 2020-06-22 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=150, verbose_name='Название типа файла')),
                ('mask', models.TextField(blank=True, max_length=4, null=True, verbose_name='Маска для автоопределения')),
            ],
            options={
                'verbose_name': 'Тип файла',
                'verbose_name_plural': 'Типы файлов',
                'permissions': [('can_add_filetype', 'Может добавлять типы файлов'), ('can_del_filetype', 'Может удалять типы файлов'), ('can_upd_filetype', 'Может изменять типы файлов')],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=150, verbose_name='Название проекта')),
                ('comments', models.TextField(max_length=2500, verbose_name='Описание проекта')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modified_projects', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'permissions': [('can_add_project', 'Может добавлять проект'), ('can_del_project', 'Может удалять проект'), ('can_view_project', 'Может просматривать файлы проекта'), ('can_upd_project', 'Может изменять проект')],
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField(max_length=100, verbose_name='Имя файла')),
                ('size', models.PositiveIntegerField(verbose_name='Размер файла')),
                ('hash', models.PositiveIntegerField(verbose_name='ХешКод целостности')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('file_path', models.FileField(upload_to='', verbose_name='Путь к файлу')),
                ('comments', models.TextField(max_length=1500, verbose_name='Комментарий')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_file', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('file_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='FileStore.FileType')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modified_file', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('version_before', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='FileStore.ProjectFile')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'permissions': [('can_add_projectfile', 'Может добавлять файлы проектов'), ('can_del_projectfile', 'Может удалять файлы проектов'), ('can_upd_projectfile', 'Может изменять файлы проектов')],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=250, unique=True, verbose_name='Метка')),
                ('files', models.ManyToManyField(blank=True, related_name='files_tags', to='FileStore.ProjectFile')),
                ('projects', models.ManyToManyField(blank=True, related_name='project_tags', to='FileStore.Project')),
            ],
            options={
                'verbose_name': 'Метка',
                'verbose_name_plural': 'Метки',
            },
        ),
    ]
