# Generated by Django 3.0.7 on 2020-06-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetype',
            name='mask',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Маска для автоопределения'),
        ),
        migrations.AlterField(
            model_name='filetype',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название типа файла'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='filename',
            field=models.CharField(max_length=100, verbose_name='Имя файла'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Метка'),
        ),
    ]
