# Generated by Django 3.0.7 on 2020-06-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileStore', '0002_auto_20200622_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='files',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='projects',
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='projects', to='FileStore.Tag'),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='files', to='FileStore.Tag'),
        ),
    ]
