# Generated by Django 3.0.7 on 2020-06-23 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FileStore', '0003_auto_20200622_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_files', to='FileStore.Project', verbose_name='Проект'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='projects', to='FileStore.Tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='comments',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='files', to='FileStore.Tag', verbose_name='Теги'),
        ),
    ]
