# Generated by Django 3.0.7 on 2020-06-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileStore', '0004_auto_20200623_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='hash',
            field=models.CharField(max_length=50, verbose_name='ХешКод целостности'),
        ),
    ]
